theme: jekyll-theme-slate
title: FusionJS Documentation
main_nav:
  - page: What is Fusion.js
    url: /
    children:
      - page: 'Framework comparison'
        url: '/framework-comparison.html'
      - page: 'Getting started'
        url: '/getting-started.html'
      - page: 'Universal code'
        url: '/universal-code.html'
      - page: 'Creating a plugin'
        url: '/creating-a-plugin.html'
        children:
          - page: 'Tokens'
            url: '/tokens.html'
          - page: 'Dependencies'
            url: '/dependencies.html'
          - page: 'Creating endpoints'
            url: '/creating-endpoints.html'
          - page: 'Creating providers'
            url: '/creating-providers.html'
          - page: 'Modifying the HTML template'
            url: '/modifying-html-template.html'
          - page: 'Working with secrets'
            url: '/working-with-secrets.html'
      - page: 'Virtual modules'
        url: '/virtual-modules.html'
